on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: ilya0100/clang_hw
    steps:
      - uses: actions/checkout@v2
      - run: cd graphs && make check

  build:
    runs-on: ubuntu-latest
    container: ilya0100/clang_hw
    needs: [check]
    steps:
    - uses: actions/checkout@v2
    - run: cd graphs && make build_tests

  test:
    runs-on: ubuntu-latest
    container: ilya0100/clang_hw
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: cd graphs && make build_tests && make run_tests

  memtest:
    runs-on: ubuntu-latest
    container: ilya0100/clang_hw
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - run: cd graphs && make memtest